from __future__ import annotations

import json
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class NormativeContractTests(unittest.TestCase):
    def test_kernel_is_small_and_direct_work_needs_no_artifact(self) -> None:
        kernel = (ROOT / "src/KERNEL.md").read_text(encoding="utf-8")
        self.assertLessEqual(len(kernel.split()), 700)
        self.assertIn("the current request may be the task boundary", kernel)
        self.assertIn("compact guardrail, not a work plan", kernel)
        self.assertFalse((ROOT / "protocols/session.md").exists())
        self.assertFalse((ROOT / "protocols/verification.md").exists())

    def test_runtime_envelope_does_not_repeat_task_or_inactive_controls(self) -> None:
        contracts = (ROOT / "src/contracts.md").read_text(encoding="utf-8")
        self.assertIn("does not repeat them", contracts)
        self.assertIn("omitted unless", contracts)
        schema = json.loads(
            (ROOT / "schemas/runtime-envelope.schema.json").read_text()
        )
        required = set(schema["required"])
        self.assertIn("profile_verified", required)
        self.assertIn("canonical_sources", required)
        self.assertNotIn("outcome", required)
        self.assertNotIn("scope", required)

    def test_program_contract_represents_repair_and_terminal_states(self) -> None:
        program = (ROOT / "protocols/program.md").read_text(encoding="utf-8")
        for phrase in (
            "independent of every invalidated field and control",
            "cannot authorize its own repair",
            "have no active coordinates or dispatchable",
            "A terminated control cannot resume",
        ):
            self.assertIn(phrase, program)

    def test_secret_recovery_closes_path_and_context(self) -> None:
        secrets = (ROOT / "protocols/secrets.md").read_text(encoding="utf-8")
        for phrase in (
            "non-secret canary or dry run",
            "pre-existing containment authority",
            "never in model context",
            "clean-context evidence",
        ):
            self.assertIn(phrase, secrets)

    def test_monolith_is_exact_normative_composition(self) -> None:
        parts = []
        for path in (
            ROOT / "src/KERNEL.md",
            ROOT / "protocols/program.md",
            ROOT / "protocols/experiment.md",
            ROOT / "protocols/secrets.md",
        ):
            parts.append(path.read_text(encoding="utf-8").strip())
        version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
        expected = (
            "<!-- Generated by scripts/build_dist.py; do not edit directly. -->\n"
            f"<!-- Noel Method version {version}. -->\n\n"
            + "\n\n---\n\n".join(parts)
            + "\n"
        )
        actual = (ROOT / "dist/MONOLITH.md").read_text(encoding="utf-8")
        self.assertEqual(actual, expected)


if __name__ == "__main__":
    unittest.main()
