#!/usr/bin/env python3
"""Build the compact modular and single-file Noel Method distributions."""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
from pathlib import Path

from methodlib import CONTEXT_KEYS, context_spec


ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
PACK = DIST / "pack"
FULL_SOURCES = [
    "src/00-preamble.md",
    "src/10-core.md",
    "src/20-vocabulary.md",
    "src/30-workflow.md",
    "src/40-contracts.md",
    "protocols/session.md",
    "protocols/program.md",
    "protocols/verification.md",
    "protocols/experiment.md",
    "protocols/secrets.md",
]


def read(source: str) -> str:
    return (ROOT / source).read_text(encoding="utf-8").strip()


def generated_header(version: str) -> str:
    return (
        "<!-- Generated by scripts/build_dist.py; do not edit directly. -->\n"
        f"<!-- Noel Method version {version}. -->\n"
    )


def navigation(prefix: str = "") -> str:
    return f"[Index]({prefix}INDEX.md) · [Base]({prefix}BASE.md)\n"


def modular_document(version: str, content: str, prefix: str = "") -> str:
    return generated_header(version) + "\n" + navigation(prefix) + "\n" + content + "\n"


def markdown_section(source: str, heading: str) -> str:
    text = read(source)
    marker = f"## {heading}"
    start = text.find(marker)
    if start < 0:
        raise ValueError(f"{source}: missing section {heading}")
    next_heading = text.find("\n## ", start + len(marker))
    return text[start:] if next_heading < 0 else text[start:next_heading].rstrip()


def render_index(version: str, spec: dict[str, object]) -> str:
    profile = spec["profile_requirement"]
    flags = spec["flags"]
    return generated_header(version) + f"""
# Noel Method Pack

Version: `{version}`

## Always load

1. [Base](BASE.md)
2. The consuming project's exact independently accepted ProjectProfile.

{profile['normal']}

If it is missing, draft, stale, or unverifiable: {profile['missing_or_invalid']}

## Context flags

Use this exact non-authoritative JSON shape:

```json
{{"program": false, "experiment": false, "secrets": false}}
```

Merge flags supplied by the caller, accepted profile, and model using boolean
OR. A model may enable a protocol but cannot disable one selected elsewhere.
Malformed or unknown fields fail closed. Flags select context; WorkContracts,
ProgramControls, and the accepted profile supply authority.

| Flag | Enable when | Load |
| --- | --- | --- |
| `program` | {flags['program']['activate_when']} | [Program](protocols/program.md) |
| `experiment` | {flags['experiment']['activate_when']} | [Experiment](protocols/experiment.md) |
| `secrets` | {flags['secrets']['activate_when']} | [Secrets](protocols/secrets.md) |

The machine-readable mapping is [`CONTEXT.json`](CONTEXT.json). Keep links one
hop from this index and pin the pack version in the ProjectProfile.

## Single-file fallback

Use [`../NOEL-METHOD.md`](../NOEL-METHOD.md) when linked local files cannot be
loaded. It is a compatibility fallback, not the normal repeated-use context.
""".lstrip()


def render_all() -> dict[Path, str]:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    spec = context_spec()
    full = generated_header(version) + "\n" + "\n\n---\n\n".join(
        read(source) for source in FULL_SOURCES
    ) + "\n"
    base = "\n\n---\n\n".join(
        [
            *(read(source) for source in (
                "src/00-preamble.md",
                "src/10-core.md",
                "src/20-vocabulary.md",
                "src/30-workflow.md",
            )),
            markdown_section("src/40-contracts.md", "WorkContract"),
            markdown_section("src/40-contracts.md", "ActionEnvelope"),
            markdown_section("src/40-contracts.md", "EvidenceRecord"),
        ]
    )
    program = "\n\n---\n\n".join(
        (
            read("protocols/program.md"),
            markdown_section("src/40-contracts.md", "ProgramControl"),
        )
    )
    project_profile = "\n\n---\n\n".join(
        (
            markdown_section("src/40-contracts.md", "ProjectProfile"),
            read("templates/project-profile.md"),
        )
    )
    rendered: dict[Path, str] = {
        DIST / "NOEL-METHOD.md": full,
        PACK / "INDEX.md": render_index(version, spec),
        PACK / "CONTEXT.json": json.dumps(
            {"method": "Noel Method", "version": version, **spec},
            indent=2,
        ) + "\n",
        PACK / "BASE.md": modular_document(version, base),
        PACK / "protocols" / "program.md": modular_document(version, program, prefix="../"),
        PACK / "protocols" / "experiment.md": modular_document(
            version, read("protocols/experiment.md"), prefix="../"
        ),
        PACK / "protocols" / "secrets.md": modular_document(
            version, read("protocols/secrets.md"), prefix="../"
        ),
        PACK / "artifacts" / "project-profile.md": modular_document(
            version, project_profile, prefix="../"
        ),
    }
    manifest_files = [
        {
            "path": str(path.relative_to(PACK)),
            "sha256": hashlib.sha256(content.encode()).hexdigest(),
        }
        for path, content in rendered.items()
        if PACK in path.parents
    ]
    manifest_files.sort(key=lambda item: item["path"])
    rendered[PACK / "MANIFEST.json"] = json.dumps(
        {
            "method": "Noel Method",
            "version": version,
            "entrypoint": "INDEX.md",
            "base": "BASE.md",
            "context_flags": list(CONTEXT_KEYS),
            "files": manifest_files,
        },
        indent=2,
    ) + "\n"
    return rendered


def check(rendered: dict[Path, str]) -> int:
    failed = False
    for path, expected in rendered.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual == expected:
            continue
        failed = True
        diff = difflib.unified_diff(
            actual.splitlines(), expected.splitlines(),
            fromfile=str(path.relative_to(ROOT)), tofile="generated", lineterm="",
        )
        print("\n".join(diff))
    expected_pack = {path for path in rendered if PACK in path.parents}
    actual_pack = {path for path in PACK.rglob("*") if path.is_file()} if PACK.exists() else set()
    extras = sorted(actual_pack - expected_pack)
    if extras:
        failed = True
        print("unexpected generated pack files:")
        for path in extras:
            print(f"- {path.relative_to(ROOT)}")
    return 1 if failed else 0


def write(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    expected_pack = {path for path in rendered if PACK in path.parents}
    for path in sorted((item for item in PACK.rglob("*") if item.is_file()), reverse=True):
        if path in expected_pack:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        if not (
            text.startswith("<!-- Generated by scripts/build_dist.py")
            or path.name == "ROUTING.json"
        ):
            raise RuntimeError(f"refusing to remove non-generated file: {path.relative_to(ROOT)}")
        path.unlink()
        print(f"removed stale {path.relative_to(ROOT)}")
    for directory in sorted((item for item in PACK.rglob("*") if item.is_dir()), reverse=True):
        if not any(directory.iterdir()):
            directory.rmdir()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_all()
    return check(rendered) if args.check else (write(rendered) or 0)


if __name__ == "__main__":
    raise SystemExit(main())
