#!/usr/bin/env python3
"""Build the self-contained Noel Method prompt pack."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "dist" / "NOEL-METHOD.md"
SOURCES = [
    "src/00-preamble.md",
    "src/10-core.md",
    "src/20-vocabulary.md",
    "src/30-workflow.md",
    "src/40-contracts.md",
    "protocols/session.md",
    "protocols/program.md",
    "protocols/verification.md",
    "protocols/experiment.md",
]


def render() -> str:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    header = (
        "<!-- Generated by scripts/build_dist.py; do not edit directly. -->\n"
        f"<!-- Noel Method version {version}. -->\n"
    )
    sections = [
        (ROOT / source).read_text(encoding="utf-8").strip()
        for source in SOURCES
    ]
    return header + "\n" + "\n\n---\n\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in distribution is stale",
    )
    args = parser.parse_args()
    expected = render()

    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual == expected:
            return 0
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(OUTPUT),
            tofile="generated",
            lineterm="",
        )
        print("\n".join(diff))
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
