#!/usr/bin/env python3
"""Build the modular and single-file Noel Method distributions."""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
PACK = DIST / "pack"
FULL_SOURCES = [
    "src/00-preamble.md",
    "src/10-core.md",
    "src/20-vocabulary.md",
    "src/30-workflow.md",
    "src/40-contracts.md",
    "protocols/session.md",
    "protocols/program.md",
    "protocols/verification.md",
    "protocols/experiment.md",
    "protocols/secrets.md",
]
PROTOCOLS = ("session", "program", "verification", "experiment", "secrets")
TEMPLATES = (
    "project-profile",
    "work-contract",
    "evidence-record",
    "program-control",
)


def read(source: str) -> str:
    return (ROOT / source).read_text(encoding="utf-8").strip()


def generated_header(version: str) -> str:
    return (
        "<!-- Generated by scripts/build_dist.py; do not edit directly. -->\n"
        f"<!-- Noel Method version {version}. -->\n"
    )


def navigation(prefix: str = "") -> str:
    return (
        f"[Index]({prefix}INDEX.md) · "
        f"[Core]({prefix}CORE.md) · "
        f"[Workflow]({prefix}WORKFLOW.md) · "
        f"[Contracts]({prefix}CONTRACTS.md)\n"
    )


def modular_document(version: str, content: str, prefix: str = "") -> str:
    return generated_header(version) + "\n" + navigation(prefix) + "\n" + content + "\n"


def render_index(version: str) -> str:
    return generated_header(version) + f"""
# Noel Method Pack

Version: `{version}`

This index is the router for progressive disclosure. Do not load every module
by default.

## Always load

1. [Core](CORE.md)
2. The consuming project's completed profile. If none exists, create one from
   the [project-profile template](templates/project-profile.md) before
   substantive work.

## Load by trigger

| Trigger | Additional modules |
| --- | --- |
| Direct, reversible task | None unless a gate or contract question appears |
| Substantive work item | [Workflow](WORKFLOW.md) and [session protocol](protocols/session.md) |
| Creating or auditing acceptance evidence | [Verification protocol](protocols/verification.md) |
| Multi-wave or dependent work | [Program protocol](protocols/program.md) and verification protocol |
| Repeated measured improvement | [Experiment protocol](protocols/experiment.md) and verification protocol |
| Secret-bearing work or suspected exposure | [Secrets protocol](protocols/secrets.md) and verification protocol |
| Creating a project or work artifact | [Contract definitions](CONTRACTS.md) and the relevant [template](templates/work-contract.md) |

## Contract templates

- [Project profile](templates/project-profile.md)
- [Work contract](templates/work-contract.md)
- [Evidence record](templates/evidence-record.md)
- [Program control](templates/program-control.md)

## Loading rules

- Follow links from this index only when their trigger applies.
- Keep references one hop from this index; do not search the pack for hidden
  requirements.
- A module may specialize the core but may not contradict it.
- Repository-specific safety and authority rules remain the local
  specialization. Surface a conflict instead of silently choosing.
- Pin this pack's version and record it in the project profile.

## Single-file fallback

If the consumer cannot follow linked local files, use
`../NOEL-METHOD.md`. The full file is a compatibility fallback, not the
recommended repeated-use context.
""".lstrip()


def render_all() -> dict[Path, str]:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    full = generated_header(version) + "\n" + "\n\n---\n\n".join(
        read(source) for source in FULL_SOURCES
    ) + "\n"
    core = "\n\n---\n\n".join(
        read(source)
        for source in ("src/00-preamble.md", "src/10-core.md", "src/20-vocabulary.md")
    )

    rendered: dict[Path, str] = {
        DIST / "NOEL-METHOD.md": full,
        PACK / "INDEX.md": render_index(version),
        PACK / "CORE.md": modular_document(version, core),
        PACK / "WORKFLOW.md": modular_document(version, read("src/30-workflow.md")),
        PACK / "CONTRACTS.md": modular_document(version, read("src/40-contracts.md")),
    }
    for name in PROTOCOLS:
        rendered[PACK / "protocols" / f"{name}.md"] = modular_document(
            version,
            read(f"protocols/{name}.md"),
            prefix="../",
        )
    for name in TEMPLATES:
        rendered[PACK / "templates" / f"{name}.md"] = modular_document(
            version,
            read(f"templates/{name}.md"),
            prefix="../",
        )

    manifest_files = {
        str(path.relative_to(PACK)): hashlib.sha256(content.encode()).hexdigest()
        for path, content in rendered.items()
        if PACK in path.parents
    }
    rendered[PACK / "MANIFEST.json"] = json.dumps(
        {
            "method": "Noel Method",
            "version": version,
            "entrypoint": "INDEX.md",
            "files": manifest_files,
        },
        indent=2,
        sort_keys=True,
    ) + "\n"
    return rendered


def check(rendered: dict[Path, str]) -> int:
    failed = False
    for path, expected in rendered.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual == expected:
            continue
        failed = True
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(path.relative_to(ROOT)),
            tofile="generated",
            lineterm="",
        )
        print("\n".join(diff))

    expected_pack = {path for path in rendered if PACK in path.parents or path == PACK}
    actual_pack = {path for path in PACK.rglob("*") if path.is_file()} if PACK.exists() else set()
    extras = sorted(actual_pack - expected_pack)
    if extras:
        failed = True
        print("unexpected generated pack files:")
        for path in extras:
            print(f"- {path.relative_to(ROOT)}")
    return 1 if failed else 0


def write(rendered: dict[Path, str]) -> None:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a checked-in distribution file is stale",
    )
    args = parser.parse_args()
    rendered = render_all()
    if args.check:
        return check(rendered)
    write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
